# Generated by Django 5.0 on 2024-06-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
